version: '3'

services:
  frontend:
    image: e-commerce-website-using-nodejs-frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    image: e-commerce-website-using-nodejs-backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
